/*
 * PFCView.java
 */

package pfc;

import com.sun.image.codec.jpeg.JPEGCodec;
import com.sun.image.codec.jpeg.JPEGImageDecoder;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.*;
import javax.swing.*;
import jigl.image.ImageNotSupportedException;
//import javax.swing.Timer;
//import javax.swing.Icon;
//import javax.swing.JDialog;
//import javax.swing.JFileChooser;
//import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class PFCView extends FrameView {

    public PFCView(SingleFrameApplication app) {
        super(app);
        
        initComponents();        
        canvasSetup();
        toolInits();
	borderInits();

        //seleccionButton.setBorder(BorderFactory.createLoweredBevelBorder());

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });

        
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = PFCApp.getApplication().getMainFrame();
            aboutBox = new PFCAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        PFCApp.getApplication().show(aboutBox);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        seleccionButton = new javax.swing.JButton();
        drawPanel = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pfc.PFCApp.class).getContext().getResourceMap(PFCView.class);
        seleccionButton.setIcon(resourceMap.getIcon("seleccionButton.icon")); // NOI18N
        seleccionButton.setToolTipText(resourceMap.getString("seleccionButton.toolTipText")); // NOI18N
        seleccionButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        seleccionButton.setFocusable(false);
        seleccionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seleccionButton.setName("seleccionButton"); // NOI18N
        seleccionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        seleccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(seleccionButton);

        drawPanel.setToolTipText(resourceMap.getString("drawPanel.toolTipText")); // NOI18N
        drawPanel.setName("drawPanel"); // NOI18N
        drawPanel.setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);
        jToolBar2.setName("jToolBar2"); // NOI18N

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversaButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);

        jButton1.setText(resourceMap.getString("procesarButton.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("procesarButton"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setName("jButton5"); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clausuraButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton5);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarizacionButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText(resourceMap.getString("newMenuItem.text")); // NOI18N
        newMenuItem.setName("newMenuItem"); // NOI18N
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText(resourceMap.getString("openMenuItem.text")); // NOI18N
        openMenuItem.setName("openMenuItem"); // NOI18N
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pfc.PFCApp.class).getContext().getActionMap(PFCView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jMenu2.setIcon(resourceMap.getIcon("jMenu2.icon")); // NOI18N
        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText(resourceMap.getString("jCheckBoxMenuItem2.text")); // NOI18N
        jCheckBoxMenuItem2.setName("jCheckBoxMenuItem2"); // NOI18N
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraer50ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText(resourceMap.getString("jCheckBoxMenuItem3.text")); // NOI18N
        jCheckBoxMenuItem3.setName("jCheckBoxMenuItem3"); // NOI18N
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraer75ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText(resourceMap.getString("jCheckBoxMenuItem1.text")); // NOI18N
        jCheckBoxMenuItem1.setName("jCheckBoxMenuItem1"); // NOI18N
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraer100ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraerPersonalizadoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenu1.add(jMenu2);

        menuBar.add(jMenu1);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuItemActionPerformed
        // TODO add your handling code here:
        miCanvas.clear();
        miCanvas.zoom();
        if (curButton == seleccionButton) {
            toolSelectall.deSelect(miCanvas);
        }
    }//GEN-LAST:event_nuevoMenuItemActionPerformed

    private void seleccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionButtonActionPerformed
        
        if (curButton == seleccionButton) {
            toolSelectall.deSelect(miCanvas);
        }
      
        curButton.setBorder(BorderFactory.createRaisedBevelBorder());
        curButton = seleccionButton;
        curButton.setBorder(BorderFactory.createLoweredBevelBorder());
        currentTool = toolSelectall;
        
        System.out.println("Salimos del evento del boton...");        
    }//GEN-LAST:event_seleccionButtonActionPerformed

    private void abrirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuItemActionPerformed
        // TODO add your handling code here:
        abrirImagen();
        miCanvas.zoom();

        imagenOriginal = miCanvas.getBufferedImage();
    }//GEN-LAST:event_abrirMenuItemActionPerformed

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void contraer50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraer50ActionPerformed
        // TODO add your handling code here:
        miCanvas.setZoom(0.5);
        miCanvas.repaint();
    }//GEN-LAST:event_contraer50ActionPerformed

    private void contraer75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraer75ActionPerformed
        // TODO add your handling code here:
        miCanvas.setZoom(0.75);
        miCanvas.repaint();
    }//GEN-LAST:event_contraer75ActionPerformed

    private void contraerPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraerPersonalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraerPersonalizadoActionPerformed

    private void contraer100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraer100ActionPerformed
        // TODO add your handling code here:
        miCanvas.setZoom(1.0);
        miCanvas.repaint();
    }//GEN-LAST:event_contraer100ActionPerformed

    private void procesarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarButtonActionPerformed
        BufferedImage bf = miCanvas.getBufferedImage();
        
        try {
            java.awt.image.BufferedImage res = Morfologia.apertura(bf, toolSelectall);
            miCanvas.setBufferedImage(res);            
        } catch (ImageNotSupportedException ex) {
            Logger.getLogger(PFCView.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("Apertura finalizada...");
    }//GEN-LAST:event_procesarButtonActionPerformed

    private void binarizacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarizacionButtonActionPerformed
        BufferedImage bf = miCanvas.getBufferedImage();

        java.awt.image.BufferedImage res = Morfologia.pasarabyn(bf, toolSelectall);
        miCanvas.setBufferedImage(res);

        System.out.println("Binarización finalizada...");
    }//GEN-LAST:event_binarizacionButtonActionPerformed

    private void resultadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoButtonActionPerformed
        // TODO add your handling code here:
        BufferedImage imagenBin = miCanvas.getBufferedImage();

        java.awt.image.BufferedImage res = Morfologia.verResultados(imagenOriginal, imagenBin, toolSelectall);
        miCanvas.setBufferedImage(res);

        System.out.println("Resultados finalizados...");
    }//GEN-LAST:event_resultadoButtonActionPerformed

    private void inversaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversaButtonActionPerformed
        // TODO add your handling code here:
        BufferedImage bf = miCanvas.getBufferedImage();

        java.awt.image.BufferedImage res = Morfologia.inversa(bf,toolSelectall);

        miCanvas.setBufferedImage(res);
        miCanvas.zoom();

        System.out.println("Inversa finalizada...");
    }//GEN-LAST:event_inversaButtonActionPerformed

    private void clausuraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clausuraButtonActionPerformed
        // TODO add your handling code here:
        BufferedImage bf = miCanvas.getBufferedImage();

        try {
            java.awt.image.BufferedImage res = Morfologia.clausura(bf, toolSelectall);
            miCanvas.setBufferedImage(res);
        } catch (ImageNotSupportedException ex) {
            Logger.getLogger(PFCView.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("Clausura finalizada...");
    }//GEN-LAST:event_clausuraButtonActionPerformed

    private void canvasSetup() {
        miCanvas = new MiCanvas();
        miCanvas.setBackground(Color.gray);
        drawPanel.add(miCanvas);

        miCanvas.zoom();        

        System.out.println("Lienzo creado correctamente...");

        miCanvas.requestFocus();
        
        miCanvas.pictureScrollPane.getViewport().setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        miCanvas.pictureScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {

            //************************MOUSE PRESSED
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                int viewX = (int) miCanvas.pictureScrollPane.getViewport().getViewPosition().getX();
                int viewY = (int) miCanvas.pictureScrollPane.getViewport().getViewPosition().getY();
                int w = miCanvas.ancho;
                int h = miCanvas.alto;

                //****************THIS IS A NORMAL CLICK                

                int newX = (evt.getX() + viewX);
                int newY = (evt.getY() + viewY);
                if ((newX < w) && (newY < h) && (newX >= 0) && (newY >= 0)) {

                    MouseEvent newEvt = new MouseEvent((Component) evt.getSource(), evt.getID(),
                            evt.getWhen(), evt.getModifiers(),
                            newX, newY, evt.getClickCount(), false);

                    currentTool.clickAction(newEvt, miCanvas);
                }
            }

            //************************MOUSE RELEASED
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                int viewX = (int) miCanvas.pictureScrollPane.getViewport().getViewPosition().getX();
                int viewY = (int) miCanvas.pictureScrollPane.getViewport().getViewPosition().getY();
                int w = miCanvas.ancho;
                int h = miCanvas.alto;
                
//                BufferedImage temp;
                

                int newX = (evt.getX() + viewX);
                int newY = (evt.getY() + viewY);

                if ((newX < w) && (newY < h) && (newX >= 0) && (newY >= 0)) {
                    MouseEvent newEvt = new MouseEvent((Component) evt.getSource(), evt.getID(),
                            evt.getWhen(), evt.getModifiers(),
                            newX, newY, evt.getClickCount(), false);
                    currentTool.mouseReleaseAction(newEvt, miCanvas);
                }

//                temp = toolSelectall.getCopyImage(miCanvas);
//                miCanvas.setBufferedImage(temp);
//                miCanvas.repaint();
            }
        });

        miCanvas.pictureScrollPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {

            //************************MOUSE DRAGGED
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                int viewX = (int) miCanvas.pictureScrollPane.getViewport().getViewPosition().getX();
                int viewY = (int) miCanvas.pictureScrollPane.getViewport().getViewPosition().getY();
                
                int newX = (evt.getX() + viewX);
                int newY = (evt.getY() + viewY);

                MouseEvent newEvt = new MouseEvent((Component) evt.getSource(), evt.getID(),
                        evt.getWhen(), evt.getModifiers(),
                        newX, newY, evt.getClickCount(), false);

                currentTool.dragAction(newEvt, miCanvas);
            }
        });
    }

    public void toolInits() {
        curButton = seleccionButton;

        toolSelectall = new selectallTool();
        //toolZoom = new zoomTool();

        currentTool = toolSelectall;
        //curZoom = zoom1;
    }

    public void borderInits() {

        seleccionButton.setBorder(BorderFactory.createLoweredBevelBorder());
      //zoom.setBorder(BorderFactory.createRaisedBevelBorder());
  }


    private void abrirImagen() {
        
        System.out.println("Cargando una nueva imagen...");

        //Creamos la ventana de selección de imagen de aplicación
        JFileChooser dialogo = new JFileChooser();
        //Creamos el filtro de archivos
        ExampleFileFilter filter = new ExampleFileFilter("jpg");
        filter.addExtension("jpeg");

        dialogo.setDialogTitle("Seleccione una imagen para mostrar...");
        dialogo.setApproveButtonText("Abrir");
        dialogo.setMultiSelectionEnabled(false);
        dialogo.setAcceptAllFileFilterUsed(false);
        dialogo.addChoosableFileFilter(filter);
        dialogo.setCurrentDirectory(new java.io.File("C:\\"));

        if (dialogo.showOpenDialog(mainPanel) == JFileChooser.APPROVE_OPTION) {
            //Recuperamos el fichero seleccionado
            File fichero = dialogo.getSelectedFile();
            
            //Si el fichero existe y puede ser leído...
            if (fichero.exists() && fichero.canRead()) {
                //Cargamos la imagen gráfica
                try {
                    FileInputStream fis = new FileInputStream(fichero);
                    JPEGImageDecoder decoder = JPEGCodec.createJPEGDecoder(fis);                    
                    miCanvas.setBufferedImage(decoder.decodeAsBufferedImage());
                    fis.close();
                } catch (IOException ex) {
                    Logger.getLogger(PFCView.class.getName()).log(Level.SEVERE, null, ex);
                }              
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel drawPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton seleccionButton;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    public MiCanvas miCanvas;
    public ourTool currentTool;
    public JButton curButton = seleccionButton;    
    public boolean resize = false;
    public BufferedImage imagenOriginal = null;

    public selectallTool toolSelectall;
    public zoomTool toolZoom;

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
